import type { Metadata } from "next";
import "./globals.css";
import { SocketProvider } from "@/context/socketContext";
import { UserLoginProvider } from "@/context/userLogincontex";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full antialiased", "font-sans", geist.variable)} suppressHydrationWarning>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <UserLoginProvider>
          <SocketProvider>{children}</SocketProvider>
        </UserLoginProvider>
      </body>
    </html>
  );
}
